### ISSUE TITLE
etcd fails with "panic: failed to unmarshal mvccpb.KeyValue" error

### ISSUE THREAD

**Issue by n549** [Netcracker/KubeMarine#241]
Kubernetes 1.23.1 deployed with Kubemarine 0.3.0. Etcd v3.5.1

Sometimes one of etcd pods fails with error:
```
{"level":"info","ts":"2022-09-14T14:13:19.477Z","caller":"mvcc/index.go:214","msg":"compact tree index","revision":2005848330}
{"level":"panic","ts":"2022-09-14T14:13:20.139Z","caller":"mvcc/watchable_store.go:414","msg":"failed to unmarshal mvccpb.KeyValue","error":"proto: KeyValue: illegal tag 0 (wire type 0)","stacktrace":"go.etcd.io/etcd/server/v3/mvcc.kvsToEvents\n\t/tmp/etcd-release-3.5.1/etcd/release/etcd/server/mvcc/watchable_store.go:414\ngo.etcd.io/etcd/server/v3/mvcc.(*watchableStore).syncWatchers\n\t/tmp/etcd-release-3.5.1/etcd/release/etcd/server/mvcc/watchable_store.go:359\ngo.etcd.io/etcd/server/v3/mvcc.(*watchableStore).syncWatchersLoop\n\t/tmp/etcd-release-3.5.1/etcd/release/etcd/server/mvcc/watchable_store.go:222"}
panic: failed to unmarshal mvccpb.KeyValue

goroutine 137 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc01e2ef080, 0xc01a408fc0, 0x1, 0x1)
        /home/remote/sbatsche/.gvm/pkgsets/go1.16.3/global/pkg/mod/go.uber.org/zap@v1.17.0/zapcore/entry.go:234 +0x58d
go.uber.org/zap.(*Logger).Panic(0xc0006868c0, 0x12268a2, 0x23, 0xc01a408fc0, 0x1, 0x1)
        /home/remote/sbatsche/.gvm/pkgsets/go1.16.3/global/pkg/mod/go.uber.org/zap@v1.17.0/logger.go:227 +0x85
go.etcd.io/etcd/server/v3/mvcc.kvsToEvents(0xc0006868c0, 0xc0004a0400, 0xc00740a000, 0x1a78, 0x2000, 0xc007300000, 0x1a78, 0x2000, 0x12, 0x7fffffffffffffff, ...)
        /tmp/etcd-release-3.5.1/etcd/release/etcd/server/mvcc/watchable_store.go:414 +0x296
go.etcd.io/etcd/server/v3/mvcc.(*watchableStore).syncWatchers(0xc0004a03c0, 0x0)
        /tmp/etcd-release-3.5.1/etcd/release/etcd/server/mvcc/watchable_store.go:359 +0x3e8
go.etcd.io/etcd/server/v3/mvcc.(*watchableStore).syncWatchersLoop(0xc0004a03c0)
        /tmp/etcd-release-3.5.1/etcd/release/etcd/server/mvcc/watchable_store.go:222 +0x1e8
created by go.etcd.io/etcd/server/v3/mvcc.newWatchableStore
        /tmp/etcd-release-3.5.1/etcd/release/etcd/server/mvcc/watchable_store.go:95 +0x3a7
```
The pod is recreated automatically by kubelet, but etcd database on this node remains corrupted. 
kube-apiserver shows different statuses for different nodes and pods.
Some nodes cannot connect to Kubernetes API, some of them cannot make changes.

**Comment by n549** [comment]
It looks like a known issue with etcd elder than v3.5.2: https://github.com/etcd-io/etcd/pull/13505.

By default etcd v3.5.3 comes with kubernetes v1.24.0. For elder k8s it's possible to use non default etcd version.

If you want to deploy a cluster with non-standard etcd version from scratch, just add `imageTag` parameter to etcd configuration in the cluster.yaml:

```
# cat cluster.yaml
...
services:
  kubeadm:
...
    etcd:
      local:
        imageTag: "3.5.3-0"
...
```
 
It's also possible to update etcd version at an existing cluster, but only during the `upgrade` procedure.

For example, if you have a cluster with k8s v1.23.1 you can upgrade it to v1.23.6 and set etcd imageTag explicitly in the cluster.yaml:

```
# cat procedure.yaml
upgrade_plan:
  - v1.23.6
# cat cluster.yaml
...
services:
  kubeadm:
...
    etcd:
      local:
        imageTag: "3.5.3-0"
...
```

**Comment by n549** [comment]
Known issue, workaround is provided.

**Comment by shaolila** [comment]
> Known issue, workaround is provided.

what is the solution, thank you
