### ISSUE TITLE
"Exception: FirewallD is still enabled" but FirewallD is not even installed

### ISSUE THREAD

**Issue by sher-tlt** [Netcracker/KubeMarine#280]
When trying to add a new node to existing cluster, it was not possible to pass FirewallD check. But in fact FirewallD was not even installed. Current validation rule assumes that it must be installed but if it does not, or broken, then installation is failed.

```
2022-11-10 14:15:07.236 +0100 DEBUG Verifying FirewallD...
2022-11-10 14:20:16.525 +0100 DEBUG 	10.109.19.135: code=3
2022-11-10 14:20:16.526 +0100 DEBUG 		STDOUT: ● firewalld.service
2022-11-10 14:20:16.526 +0100 DEBUG 		           Loaded: masked (/dev/null; bad)
2022-11-10 14:20:16.526 +0100 DEBUG 		           Active: inactive (dead)
2022-11-10 14:20:16.526 +0100 DEBUG 		        
2022-11-10 14:20:16.527 +0100 CRITICAL FAILURE!
2022-11-10 14:20:16.527 +0100 CRITICAL 'add_node' procedure failed.
2022-11-10 14:20:16.527 +0100 CRITICAL KME0001: Unexpected exception
2022-11-10 14:20:16.527 +0100 Traceback (most recent call last):
2022-11-10 14:20:16.527 +0100   File "/opt/kubemarine/kubemarine/core/flow.py", line 66, in run_actions
2022-11-10 14:20:16.528 +0100     act.run(resources)
2022-11-10 14:20:16.528 +0100   File "/opt/kubemarine/kubemarine/procedures/add_node.py", line 129, in run
2022-11-10 14:20:16.528 +0100     flow.run_tasks(res, tasks, cumulative_points=install.cumulative_points)
2022-11-10 14:20:16.529 +0100   File "/opt/kubemarine/kubemarine/core/flow.py", line 146, in run_tasks
2022-11-10 14:20:16.529 +0100     run_flow(filtered_tasks, cluster, cumulative_points)
2022-11-10 14:20:16.530 +0100   File "/opt/kubemarine/kubemarine/core/flow.py", line 243, in run_flow
2022-11-10 14:20:16.530 +0100     run_flow(task, cluster, cumulative_points, __task_path)
2022-11-10 14:20:16.531 +0100   File "/opt/kubemarine/kubemarine/core/flow.py", line 243, in run_flow
2022-11-10 14:20:16.531 +0100     run_flow(task, cluster, cumulative_points, __task_path)
2022-11-10 14:20:16.532 +0100   File "/opt/kubemarine/kubemarine/core/flow.py", line 230, in run_flow
2022-11-10 14:20:16.532 +0100     proceed_cumulative_point(cluster, cumulative_points, __task_path)
2022-11-10 14:20:16.533 +0100   File "/opt/kubemarine/kubemarine/core/flow.py", line 383, in proceed_cumulative_point
2022-11-10 14:20:16.534 +0100     call_result = cluster.nodes["all"].get_new_nodes_or_self().call(func)
2022-11-10 14:20:16.534 +0100   File "/opt/kubemarine/kubemarine/core/group.py", line 586, in call
2022-11-10 14:20:16.535 +0100     return self.call_batch([action], **{"%s.%s" % (action.__module__, action.__name__): kwargs})
2022-11-10 14:20:16.536 +0100   File "/opt/kubemarine/kubemarine/core/group.py", line 600, in call_batch
2022-11-10 14:20:16.536 +0100     results[action] = action(self, **action_kwargs)
2022-11-10 14:20:16.537 +0100   File "/opt/kubemarine/kubemarine/system.py", line 662, in verify_system
2022-11-10 14:20:16.537 +0100     raise Exception("FirewallD is still enabled")
2022-11-10 14:20:16.537 +0100 Exception: FirewallD is still enabled
```

**Comment by koryaga** [comment]
@dmyar21  pls assess

**Comment by ilia1243** [comment]
> Current validation rule assumes that it must be installed

I have not installed FirewallD on Centos 7 and have the following
```
$ sudo systemctl status firewalld
Unit firewalld.service could not be found.
$ echo $?
4
```
Exit code is 4 so it should be considered as disabled https://github.com/Netcracker/KubeMarine/blob/0.9.0/kubemarine/system.py#L386

Could you share your OS version on which you have FirewallD not installed?

**Comment by sher-tlt** [comment]
```
[root@ncm-worker-4 ~]# cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)
[root@ncm-worker-4 ~]# uname -a
Linux ncm-worker-4 3.10.0-1160.76.1.el7.x86_64 #1 SMP Wed Aug 10 16:21:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
[root@ncm-worker-4 ~]#
```

**Comment by dmyar21** [comment]
Hello @sher-tlt 
Please send us a test case with your problem
