### ISSUE TITLE
migrate_kubemarine procedure  fires exception

### ISSUE THREAD

**Issue by koryaga** [Netcracker/KubeMarine#612]
_#./kubemarine-macos11-arm64-v0.27.0  migrate_kubemarine --list_
```
No patches available.
Traceback (most recent call last):
  File "kubemarine/__main__.py", line 238, in <module>
  File "kubemarine/__main__.py", line 166, in main
  File "kubemarine/procedures/migrate_kubemarine.py", line 510, in main
  File "kubemarine/procedures/migrate_kubemarine.py", line 457, in run
NameError: name 'exit' is not defined
[21228] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by koryaga** [comment]
@ilia1243 FYI
