### ISSUE TITLE
ValueError: q must be exactly 160, 224, or 256 bits long

### ISSUE THREAD

**Issue by kolchanov** [Netcracker/KubeMarine#710]
It seems that paramiko can't properly connect to remote host

I have configuration:
node_defaults:
  keyfile: "/home/ubuntu/.ssh/id_rsa" 
  password: ""
  username: "ubutu"

nodes:
  - name: "k8s-control-plane-1"
    address: "10.0.1.10"
    internal_address: "192.168.8.10"
    roles: ["balancer", "control-plane"]
.....

And I get error:

Loading inventory file 'cluster.yaml'
2024-12-27 21:53:48,953 DEBUG Start detecting nodes context...
Unknown exception: q must be exactly 160, 224, or 256 bits long
Unknown exception: q must be exactly 160, 224, or 256 bits long
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/pipx/venvs/kubemarine/lib/python3.12/site-packages/paramiko/transport.py", line 2234, in run
    handler(m)
  File "/home/ubuntu/.local/share/pipx/venvs/kubemarine/lib/python3.12/site-packages/paramiko/auth_handler.py", line 404, in _parse_service_accept
    sig = self.private_key.sign_ssh_data(blob, algorithm)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/share/pipx/venvs/kubemarine/lib/python3.12/site-packages/paramiko/dsskey.py", line 120, in sign_ssh_data
    ).private_key(backend=default_backend())
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: q must be exactly 160, 224, or 256 bits long

**Comment by kolchanov** [comment]
I have no problem with ssh client

**Comment by iagusev** [comment]
@kolchanov Hello!
Could you check is it typo in this thread or you have the same in config: `username: "ubutu"` ?

**Comment by kolchanov** [comment]
Thank you.
I can check in few days.

**Comment by kolchanov** [comment]
Yes, you are right! Typo was the root cause.
But for me message must be more correct

**Comment by kolchanov** [comment]
Typo was the root cause.
